/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.cedetel.android.tigre;

public final class R {
    public static final class array {
        public static final int categArray=0x7f040002;
        public static final int color=0x7f040003;
        public static final int grosor=0x7f040004;
        public static final int opcionvista=0x7f040000;
        public static final int transparencia=0x7f040005;
        public static final int zoomarray=0x7f040001;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int blue=0x7f060002;
        public static final int colorTexto=0x7f060007;
        public static final int green=0x7f060003;
        public static final int indian_red=0x7f060005;
        public static final int medium_aquamarine=0x7f060006;
        public static final int red=0x7f060001;
        public static final int white=0x7f060000;
        public static final int yellow=0x7f060004;
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int btn_star=0x7f020001;
        public static final int camera=0x7f020002;
        public static final int camera_icon=0x7f020003;
        public static final int car_yellow=0x7f020004;
        public static final int carpeta=0x7f020005;
        public static final int checked=0x7f020006;
        public static final int close=0x7f020007;
        public static final int coche=0x7f020008;
        public static final int connect=0x7f020009;
        public static final int dibujar=0x7f02000a;
        public static final int flag_icon=0x7f02000b;
        public static final int house_icon=0x7f02000c;
        public static final int house_small_icon=0x7f02000d;
        public static final int huella_small=0x7f02000e;
        public static final int huellacirculo2=0x7f02000f;
        public static final int icon=0x7f020010;
        public static final int lupa=0x7f020011;
        public static final int mappin_a=0x7f020012;
        public static final int mappin_b=0x7f020013;
        public static final int mappin_blue=0x7f020014;
        public static final int mappin_red=0x7f020015;
        public static final int mappinr=0x7f020016;
        public static final int mappiny=0x7f020017;
        public static final int navajo_white=0x7f020027;
        public static final int papelera=0x7f020018;
        public static final int pasos=0x7f020019;
        public static final int perdida=0x7f02001a;
        public static final int plano=0x7f02001b;
        public static final int save=0x7f02001c;
        public static final int screen_background_black=0x7f020028;
        public static final int sokotan=0x7f02001d;
        public static final int star_icon=0x7f02001e;
        public static final int tigre=0x7f02001f;
        public static final int tomar=0x7f020020;
        public static final int translucent_background=0x7f020029;
        public static final int transparent_background=0x7f02002a;
        public static final int tree_icon=0x7f020021;
        public static final int wifi=0x7f020022;
        public static final int world=0x7f020023;
        public static final int zodiac=0x7f020024;
        public static final int zoomin=0x7f020025;
        public static final int zoomout=0x7f020026;
    }
    public static final class id {
        public static final int PhotoList=0x7f070047;
        public static final int Ptag=0x7f07004f;
        public static final int Ptitle=0x7f07004e;
        public static final int Rtitle=0x7f070050;
        public static final int TxtSpinner1=0x7f07000f;
        public static final int TxtSpinner2=0x7f070012;
        public static final int TxtSpinner3=0x7f070014;
        public static final int TxtSpinner4=0x7f070016;
        public static final int altitude=0x7f07006f;
        public static final int arbol=0x7f07003a;
        public static final int autodetectar=0x7f070007;
        public static final int body=0x7f070056;
        public static final int botonActualizar=0x7f07005c;
        public static final int botonBorrar=0x7f070018;
        public static final int botonBorrarTigre=0x7f07006a;
        public static final int botonCamara=0x7f070022;
        public static final int botonConfig=0x7f070019;
        public static final int botonConsulta=0x7f07001f;
        public static final int botonFoto=0x7f070051;
        public static final int botonFotoA=0x7f070052;
        public static final int botonGuardar=0x7f07003c;
        public static final int botonGuardarTigre=0x7f07006b;
        public static final int botonInicio=0x7f07003e;
        public static final int botonPunto=0x7f070021;
        public static final int botonReset=0x7f07006c;
        public static final int botonRuta=0x7f07005b;
        public static final int botonSituar=0x7f070073;
        public static final int botonStop=0x7f070023;
        public static final int checkGirar=0x7f07005d;
        public static final int chinazul=0x7f070036;
        public static final int chinroja=0x7f070035;
        public static final int comentPunto=0x7f070032;
        public static final int comentarios=0x7f070055;
        public static final int contrasena=0x7f070003;
        public static final int coordenadas=0x7f07001b;
        public static final int creageisha=0x7f070030;
        public static final int distancia=0x7f070063;
        public static final int distancia100=0x7f070065;
        public static final int distancia200=0x7f070066;
        public static final int distancia50=0x7f070064;
        public static final int distancia500=0x7f070067;
        public static final int etiqueta=0x7f070057;
        public static final int flag=0x7f07003b;
        public static final int gallery=0x7f070042;
        public static final int geishalist=0x7f07004d;
        public static final int guardar=0x7f07000b;
        public static final int icono=0x7f070025;
        public static final int iconoRadio=0x7f070034;
        public static final int iconoRadio2=0x7f070038;
        public static final int imagen=0x7f070071;
        public static final int intheend=0x7f07000c;
        public static final int latitude=0x7f07006d;
        public static final int layout=0x7f070000;
        public static final int lineaSpinner=0x7f070026;
        public static final int longitude=0x7f07006e;
        public static final int manual=0x7f070008;
        public static final int map=0x7f070040;
        public static final int mapaFotos=0x7f070041;
        public static final int marcaa=0x7f070037;
        public static final int marcab=0x7f070039;
        public static final int modo=0x7f07001a;
        public static final int mspinner=0x7f07005a;
        public static final int nombreFoto=0x7f070049;
        public static final int nombrePunto=0x7f070031;
        public static final int nombreRuta=0x7f070053;
        public static final int nombreUsuario=0x7f070001;
        public static final int nosave=0x7f07000e;
        public static final int onscreen_menu=0x7f070072;
        public static final int opcSelect=0x7f07000a;
        public static final int opcionesGuardar=0x7f070009;
        public static final int password=0x7f070004;
        public static final int puntoslist=0x7f070046;
        public static final int realtime=0x7f07000d;
        public static final int regiongeisha=0x7f07002b;
        public static final int resultadoPuntos=0x7f070045;
        public static final int resultadoRutas=0x7f070043;
        public static final int rutasGeisha=0x7f07004c;
        public static final int rutaslist=0x7f070044;
        public static final int serviciogeisha=0x7f07002c;
        public static final int spinner1=0x7f070010;
        public static final int spinner2=0x7f070013;
        public static final int spinner3=0x7f070015;
        public static final int spinner4=0x7f070017;
        public static final int spinner5=0x7f07001c;
        public static final int spinner6=0x7f07001d;
        public static final int spinner7=0x7f07001e;
        public static final int spinnerColorLinea=0x7f070069;
        public static final int spinnerColorPunto=0x7f070068;
        public static final int subtitulo=0x7f07003f;
        public static final int tag=0x7f070058;
        public static final int tagFoto=0x7f07004a;
        public static final int tagsgeisha=0x7f07002e;
        public static final int tcreageisha=0x7f07002f;
        public static final int text1=0x7f070024;
        public static final int textServicios=0x7f070059;
        public static final int texto=0x7f070033;
        public static final int thumb=0x7f070048;
        public static final int tiempo=0x7f07005e;
        public static final int tiempo10=0x7f07005f;
        public static final int tiempo30=0x7f070060;
        public static final int tiempo300=0x7f070062;
        public static final int tiempo60=0x7f070061;
        public static final int tigrelist=0x7f07004b;
        public static final int time=0x7f070070;
        public static final int title=0x7f070054;
        public static final int titulo=0x7f070020;
        public static final int titulogeisha=0x7f070027;
        public static final int titulorutas=0x7f070028;
        public static final int ttagsgeisha=0x7f07002d;
        public static final int tusuariogeisha=0x7f070029;
        public static final int tv0=0x7f070011;
        public static final int txtfile=0x7f07003d;
        public static final int user=0x7f070002;
        public static final int usuariogeisha=0x7f07002a;
        public static final int zona=0x7f070006;
        public static final int zonaSelect=0x7f070005;
    }
    public static final class layout {
        public static final int configuracion=0x7f030000;
        public static final int consulta_info_geo=0x7f030001;
        public static final int control_service=0x7f030002;
        public static final int elemento=0x7f030003;
        public static final int fila=0x7f030004;
        public static final int geisha_info=0x7f030005;
        public static final int interes=0x7f030006;
        public static final int leer_ruta=0x7f030007;
        public static final int main=0x7f030008;
        public static final int mapa=0x7f030009;
        public static final int mapa_fotos=0x7f03000a;
        public static final int mi_consulta=0x7f03000b;
        public static final int mis_fotos=0x7f03000c;
        public static final int mis_puntos=0x7f03000d;
        public static final int mis_puntos_ruta=0x7f03000e;
        public static final int mis_rutas=0x7f03000f;
        public static final int nueva_foto=0x7f030010;
        public static final int nueva_ruta=0x7f030011;
        public static final int opciones_tigre=0x7f030012;
        public static final int ruta_row=0x7f030013;
        public static final int simgps=0x7f030014;
        public static final int ver_foto=0x7f030015;
    }
    public static final class string {
        public static final int add_tags=0x7f05004e;
        public static final int altitude=0x7f05005a;
        public static final int app_complete=0x7f050046;
        /**  TITULO APLICACION 
         */
        public static final int app_name=0x7f050045;
        public static final int autodetect=0x7f050011;
        public static final int botonActualizar=0x7f05000a;
        public static final int botonBorrar=0x7f050009;
        public static final int botonCamara=0x7f05000b;
        public static final int botonEnviar=0x7f050007;
        public static final int botonFoto=0x7f05000c;
        public static final int botonGuardar=0x7f050005;
        /**  BOTONES 
         */
        public static final int botonInicio=0x7f050000;
        public static final int botonMostrar=0x7f050008;
        public static final int botonPunto=0x7f050006;
        public static final int botonRuta=0x7f050004;
        public static final int botonService=0x7f050001;
        public static final int botonSituarFoto=0x7f05000d;
        public static final int botonStart=0x7f050002;
        public static final int botonStop=0x7f050003;
        public static final int categoria=0x7f050019;
        public static final int colorLinea=0x7f050028;
        public static final int colorPunto=0x7f050027;
        public static final int comentPunto=0x7f050050;
        public static final int comentarios=0x7f05004d;
        public static final int contrasena=0x7f05000f;
        /**  DIALOGO INICIO DE RUTA 
         */
        public static final int dialog=0x7f050054;
        /**  DIALOGO FOTO NUEVA 
         */
        public static final int dialogoFoto=0x7f050057;
        public static final int diseno=0x7f05001a;
        public static final int distanciaGPS=0x7f050021;
        public static final int error_seleccion=0x7f050018;
        public static final int error_user=0x7f050017;
        public static final int finalizar=0x7f050016;
        public static final int iconos=0x7f050026;
        public static final int latitude=0x7f050058;
        public static final int longitude=0x7f050059;
        public static final int manual=0x7f050012;
        /**  MENU PRINCIPAL 
         */
        public static final int menu1=0x7f050029;
        public static final int menu11mapa=0x7f050033;
        public static final int menu12mapa=0x7f050034;
        public static final int menu13mapa=0x7f050035;
        /**  MENU MAPA, DIBUJAR RUTA 
         */
        public static final int menu1dibujar=0x7f050036;
        public static final int menu1foto=0x7f05003a;
        /**  MENU MAPA, NUEVA RUTA 
         */
        public static final int menu1mapa=0x7f05002e;
        /**  MENU PUNTO 
         */
        public static final int menu1punto=0x7f050039;
        public static final int menu2=0x7f05002a;
        public static final int menu2dibujar=0x7f050037;
        public static final int menu2foto=0x7f05003b;
        public static final int menu2mapa=0x7f05002f;
        public static final int menu3=0x7f05002b;
        public static final int menu3dibujar=0x7f050038;
        public static final int menu3foto=0x7f05003c;
        public static final int menu3mapa=0x7f050030;
        public static final int menu4=0x7f05002c;
        public static final int menu4foto=0x7f05003d;
        public static final int menu5=0x7f05002d;
        public static final int menu6mapa=0x7f050031;
        public static final int menu8mapa=0x7f050032;
        public static final int menuBorrar=0x7f050042;
        public static final int menuBuscar=0x7f050044;
        /**  COMPARTIDO 
         */
        public static final int menuCapas=0x7f05003e;
        public static final int menuEditar=0x7f050040;
        public static final int menuGuardar=0x7f050041;
        public static final int menuSalir=0x7f050043;
        public static final int menuZoom=0x7f05003f;
        public static final int no=0x7f050056;
        public static final int noguardar=0x7f050014;
        /**  RUTA, PUNTO Y FOTOS 
         */
        public static final int nombre=0x7f05004c;
        public static final int nombrePunto=0x7f05004f;
        /**  GEISHA CONFIGURACION
         */
        public static final int nombreUsuario=0x7f05000e;
        /**  OPCIONES TIGRE 
         */
        public static final int opciones=0x7f05001b;
        public static final int opcionesGuardar=0x7f050013;
        public static final int ponTitulo=0x7f050053;
        /**  ERRORES 
         */
        public static final int ponTituloFoto=0x7f050051;
        public static final int radio100m=0x7f050023;
        public static final int radio10seg=0x7f05001d;
        public static final int radio1min=0x7f05001f;
        public static final int radio200m=0x7f050024;
        public static final int radio30seg=0x7f05001e;
        public static final int radio500m=0x7f050025;
        public static final int radio50m=0x7f050022;
        public static final int radio5min=0x7f050020;
        public static final int startService=0x7f050049;
        /**  GPS SERVICE CONTROLLER 
         */
        public static final int statusText1=0x7f050047;
        public static final int statusText2=0x7f050048;
        public static final int stopService=0x7f05004a;
        public static final int submenu=0x7f05004b;
        public static final int tiempoGPS=0x7f05001c;
        public static final int tiemporeal=0x7f050015;
        public static final int time=0x7f05005b;
        public static final int yaHayRuta=0x7f050052;
        public static final int yes=0x7f050055;
        public static final int zona=0x7f050010;
    }
}
